backend:
  name: git-gateway
  branch: master # Branch to update on github repo


# Optional setting to enable editorial workflow, which adds an interface for drafting, and reviewing prior to pushing the post

#publish_mode: editorial_workflow

# Relative path where uploaded images are stored. Global path in gatsbyjs begins in the /static directory
media_folder: 'static/images/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/images/uploads' # The src attribute in HTML for uploaded media will begin with /images/uploads

# Collections define the structure of different content types that are managed by netlify-cms

collections:
  - name: 'news' # Used in routes.
    label: 'News' # Used in the admin UI for post types
    folder: 'src/pages/news' # The path to the folder where the documents are stored. For a gatsbyjs markdown files would be created in /src/pages/news
    create: true # Allows the user to create new documents in this collection through netlify-cms
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template ex. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually stored in the front matter
      - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'news-post'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Featured Image', name: 'image', widget: 'image'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Description', name: 'description', widget: 'text'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
      # Fields shown in the admin UI
      #   label: Field label in the admin UI
      #   name: Field name in the document front matter
      #   widget: Determines UI style and value data type
      #   default (optional): Sets a default value for the field

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Image', name: 'image', widget: 'image'}
          - {label: 'Heading', name: 'heading', widget: 'string'}
          - {label: 'About', name: 'about', widget: 'object', fields: [{label: 'Title', name: 'title', widet: 'string'}, {label: 'Image', name: 'image', widet: 'image'}, {label: 'Body', name: 'body', widget: 'text'}]}
          - {label: 'Work', name: 'work', widget: 'object', fields: [{label: 'Title', name: 'title', widet: 'string'}, {label: 'Image', name: 'image', widet: 'image'}, {label: 'Body', name: 'body', widget: 'text'}]}
      - file: 'src/pages/about.md'
        label: 'About Page'
        name: 'about'
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'about-page'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Image', name: 'image', widget: 'image'}
          - {label: 'Body', name: 'body', widget: 'markdown'}
      - file: 'src/pages/operations.md'
        label: 'Operations Page'
        name: 'operations'
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'operations-page'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Image', name: 'image', widget: 'image'}
          - {label: 'Body', name: 'body', widget: 'markdown'}
      - file: 'src/pages/responsibility.md'
        label: 'Responsibility Page'
        name: 'responsibility'
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'responsibility-page'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Image', name: 'image', widget: 'image'}
          - {label: 'Body', name: 'body', widget: 'markdown'}
      - file: 'src/pages/news/index.md'
        label: 'News Page'
        name: 'news'
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'news-page'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Image', name: 'image', widget: 'image'}
      - file: 'src/pages/contact.md'
        label: 'Contact Page'
        name: 'contact'
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'contact-page'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Image', name: 'image', widget: 'image'}
          - {label: 'English Address', name: 'addressEn', widget: 'string'}
          - {label: 'English Address Line Two', name: 'addressTwoEn', widget: 'string'}
          - {label: 'English Phone', name: 'phoneEn', widget: 'string'}
          - {label: 'English Direct', name: 'directEn', widget: 'string'}
          - {label: 'English Fax', name: 'faxEn', widget: 'string'}
          - {label: 'English Email', name: 'emailEn', widget: 'string'}
          - {label: 'German Address', name: 'addressDe', widget: 'string'}
          - {label: 'German Phone', name: 'phoneDe', widget: 'string'}
          - {label: 'German FAx', name: 'faxDe', widget: 'string'}
          - {label: 'German Email', name: 'emailDe', widget: 'string'}
