backend:
  name: git-gateway
  branch: master # Branch to update on github repo

# Optional setting to enable editorial workflow, which adds an interface for drafting, and reviewing prior to pushing the post

#publish_mode: editorial_workflow

# Relative path where uploaded images are stored. Global path in gatsbyjs begins in the /static directory
media_folder: static/images/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /images/uploads # The src attribute in HTML for uploaded media will begin with /images/uploads

# Collections define the structure of different content types that are managed by the netlify-cms

collections:
  - name: news # Used in routes.
    label: News # Used in the admin UI for post types
    folder: src/pages/news # The path to the folder where the documents are stored. For a gatsbyjs markdown files would be created in /src/pages/news
    create: true # Allows the user to create new documents in this collection through netlify-cms
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template ex. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually stored in the front matter
      - label: Template Key
        name: templateKey
        widget: hidden
        default: news-post
      - label: Publish
        name: publish
        widget: boolean
        default: true
      - label: Title
        name: title
        widget: string
      - label: Hero
        name: hero
        widget: image
        default: /images/uploads/mark-koch-kirln3jjvnu-unsplash.jpg
      - label: Featured Image
        name: image
        widget: image
        required: false
      - label: Category
        name: category
        widget: select
        options: ["General", "Germany", "Poland"]
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
        required: false
      - label: Body
        name: body
        widget: markdown
      # Fields shown in the admin UI
      #   label: Field label in the admin UI
      #   name: Field name in the document front matter
      #   widget: Determines UI style and value data type
      #   default (optional): Sets a default value for the field
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Landing Page
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index-page
          - label: Title
            name: title
            widget: string
          - label: Hero
            name: hero
            widget: image
            default: /images/uploads/mark-koch-kirln3jjvnu-unsplash.jpg
          - label: Location Buttons
            name: locations
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Image
                name: image
                widget: image
              - label: Body
                name: body
                widget: markdown
          - label: Highlights Section
            name: highlights
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Images
                name: images
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
              - label: Content
                name: data
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Body
                    name: body
                    widget: markdown
          - label: Map Section
            name: map
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Image
                name: image
                widget: image
          - label: News Section
            name: news
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
      - file: src/pages/about.md
        label: About Page
        name: about
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: about-page
          - label: Title
            name: title
            widget: string
          - label: Hero
            name: hero
            widget: image
            default: /images/uploads/mark-koch-kirln3jjvnu-unsplash.jpg
          - label: Highlights Section
            name: highlights
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Images
                name: images
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
              - label: Content
                name: data
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Body
                    name: body
                    widget: markdown
          - label: Features Section
            name: features
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Body
                name: body
                widget: markdown
      - file: src/pages/operations.md
        label: Operations Page
        name: operations
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: operations-page
          - label: Title
            name: title
            widget: string
          - label: Hero
            name: hero
            widget: image
            default: /images/uploads/mark-koch-kirln3jjvnu-unsplash.jpg
          - label: Showcase Section
            name: showcase
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Default Section
                name: main
                widget: markdown
              - label: Secondary Sections
                name: data
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Image
                    name: image
                    widget: image
                  - label: Body
                    name: body
                    widget: markdown
      - file: src/pages/news.md
        label: News Page
        name: news
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: news-page
          - label: Title
            name: title
            widget: string
          - label: Hero
            name: hero
            widget: image
            default: /images/uploads/mark-koch-kirln3jjvnu-unsplash.jpg
      - file: src/pages/responsibility.md
        label: Responsibility Page
        name: responsibility
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: responsibility-page
          - label: Title
            name: title
            widget: string
          - label: Hero
            name: hero
            widget: image
            default: /images/uploads/mark-koch-kirln3jjvnu-unsplash.jpg
          - label: Highlights Section
            name: highlights
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Images
                name: images
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
              - label: Content
                name: data
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Body
                    name: body
                    widget: markdown
      - file: src/pages/contact.md
        label: Contact Page
        name: contact
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: contact-page
          - label: Title
            name: title
            widget: string
          - label: Hero
            name: hero
            widget: image
            default: /images/uploads/mark-koch-kirln3jjvnu-unsplash.jpg
          - label: Main Contact Information
            name: main
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Name
                name: name
                widget: string
              - label: Image
                name: image
                widget: image
              - label: Contact Information
                name: data
                widget: list
          - label: Secondary Contact Information
            name: secondary
            widget: list
            fields:
              - label: Name
                name: title
                widget: string
              - label: Contact Information
                name: data
                widget: list

  - name: polandPages
    label: Poland Pages
    files:
      - file: src/pages/pl/index.md
        label: Main Page
        name: pl
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: pl-page
          - label: Title
            name: title
            widget: string
          - label: Hero
            name: hero
            widget: image
            default: /images/uploads/mark-koch-kirln3jjvnu-unsplash.jpg
          - label: Highlights Section
            name: highlights
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Images
                name: images
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
              - label: Content
                name: data
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Body
                    name: body
                    widget: markdown
          - label: Map Section
            name: map
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Image
                name: image
                widget: image
              - label: Body
                name: body
                widget: markdown
          - label: News Section
            name: news
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
      - file: src/pages/pl/wolin.md
        label: Wolin Page
        name: wolin
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: pl-post
          - label: Title
            name: title
            widget: string
          - label: Hero
            name: hero
            widget: image
            default: /images/uploads/mark-koch-kirln3jjvnu-unsplash.jpg
          - label: Map Section
            name: map
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Image
                name: image
                widget: image
              - label: Body
                name: body
                widget: markdown
          - label: Features Section
            name: features
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Body
                name: body
                widget: markdown
