backend:
  name: git-gateway
  branch: master # Branch to update on github repo


# Optional setting to enable editorial workflow, which adds an interface for drafting, and reviewing prior to pushing the post

#publish_mode: editorial_workflow

# Relative path where uploaded images are stored. Global path in gatsbyjs begins in the /static directory
media_folder: 'static/images/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/images/uploads' # The src attribute in HTML for uploaded media will begin with /images/uploads

# Collections define the structure of different content types that are managed by netlify-cms

collections:
  - name: 'news' # Used in routes.
    label: 'News' # Used in the admin UI for post types
    folder: 'src/pages/news' # The path to the folder where the documents are stored. For a gatsbyjs markdown files would be created in /src/pages/news
    create: true # Allows the user to create new documents in this collection through netlify-cms
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template ex. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually stored in the front matter
      - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'news-post'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Featured Image', name: 'image', widget: 'image', required: false}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Description', name: 'description', widget: 'text', required: false}
      - {label: 'Body', name: 'body', widget: 'markdown'}
      # Fields shown in the admin UI
      #   label: Field label in the admin UI
      #   name: Field name in the document front matter
      #   widget: Determines UI style and value data type
      #   default (optional): Sets a default value for the field

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Image', name: 'image', widget: 'image'}
          - {label: 'Heading', name: 'heading', widget: 'string'}
          - {label: 'Picture One', name: 'picOne', widget: 'image'}
          - {label: 'Picture Two', name: 'picTwo', widget: 'image'}
          - {label: 'Picture Three', name: 'picThree', widget: 'image'}
          - {label: 'About', name: 'about', widget: 'object', fields: [{label: 'Title', name: 'title', widet: 'string'}, {label: 'Body', name: 'body', widget: 'text'}]}
          - {label: 'Work', name: 'work', widget: 'object', fields: [{label: 'Title', name: 'title', widet: 'string'} {label: 'Body', name: 'body', widget: 'text'}]}
      - file: 'src/pages/about.md'
        label: 'About Page'
        name: 'about'
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'about-page'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'CEP Management', name: 'management', widget: 'markdown'}
          - {label: 'CEP Board of Directors', name: 'boardOfDirectors', widget: 'markdown'}
          - {label: 'Picture One', name: 'picOne', widget: 'image'}
          - {label: 'Picture Two', name: 'picTwo', widget: 'image'}
          - {label: 'Picture Three', name: 'picThree', widget: 'image'}
          - {label: 'Body', name: 'body', widget: 'markdown'}
      - file: 'src/pages/operations.md'
        label: 'Operations Page'
        name: 'operations'
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'operations-page'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'German Operations', name: 'germanyOps', widget: 'markdown'}
          - {label: 'Polish Operations', name: 'polishOps', widget: 'markdown'}
      - file: 'src/pages/responsibility.md'
        label: 'Responsibility Page'
        name: 'responsibility'
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'responsibility-page'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Picture One', name: 'picOne', widget: 'image'}
          - {label: 'Picture Two', name: 'picTwo', widget: 'image'}
          - {label: 'Picture Three', name: 'picThree', widget: 'image'}
          - {label: 'Body', name: 'body', widget: 'markdown'}
      - file: 'src/pages/news/index.md'
        label: 'News Page'
        name: 'news'
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'news-page'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Image', name: 'image', widget: 'image'}
      - file: 'src/pages/contact.md'
        label: 'Contact Page'
        name: 'contact'
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'contact-page'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Canadian Pic', name: 'picEn', widget: 'image'}
          - {label: 'German Pic', name: 'picDe', widget: 'image'}
          - {label: 'English Contact', name: 'contactEn', widget: 'text'}
          - {label: 'German Contact', name: 'contactDe', widget: 'text'}
